// 图片主色 / 调色板提取（浏览器 ESM + extract-colors.wasm）
// 默认导出 extractColors；initExtractColorsWasm 可显式预加载。
// 默认从内联 base64 bytes 实例化，避免浏览器扩展/隐私盾牌拦截 .wasm fetch。

const EXTRACT_COLORS_WASM_BASE64 = "AGFzbQEAAAABQwpgAX8Bf2ACf38AYAJ/fwF/YAN/f38AYAF/AGADf35/AX9gCn9/f398fHx8f38Bf2AFf39/f38AYAN/f38Bf2AAAX8CKQEWd2FzaV9zbmFwc2hvdF9wcmV2aWV3MQ5jbG9ja190aW1lX2dldAAFAxMSAAYCAwMBBwEAAQgABAEAAAQJBAUBcAEDAwUGAQGCAoICBggBfwFBsKwECweTAQYGbWVtb3J5AgARZ2V0X3BpeGVsc19idWZmZXIAARtleHRyYWN0X2NvbG9yc19mcm9tX3JnYmFfanMAAhlfX2luZGlyZWN0X2Z1bmN0aW9uX3RhYmxlAQAZX2Vtc2NyaXB0ZW5fc3RhY2tfcmVzdG9yZQARHGVtc2NyaXB0ZW5fc3RhY2tfZ2V0X2N1cnJlbnQAEgkIAQBBAQsCAwsMAQEKxn8SsAgBDH9BlAgoAgAhCUGQCCgCACAATwRAIAkPCwJ/IAlFBEAgABAMDAELIABBQE8EQEGsKEEwNgIAQQAMAQsCf0EQIABBC2pBeHEgAEELSRshBSAJQQhrIgMoAgQiCEF4cSEHAkAgCEEDcUUEQCAFQYACSQ0BIAVBBGogB00EQCADIQEgByAFa0GYLCgCAEEBdE0NAgtBAAwCCyADIAdqIQYCQCAFIAdNBEAgByAFayICQRBJDQEgAyAFIAhBAXFyQQJyNgIEIAMgBWoiASACQQNyNgIEIAYgBigCBEEBcjYCBCABIAIQDgwBC0HQKCgCACAGRgRAQcQoKAIAIAdqIgcgBU0NAiADIAUgCEEBcXJBAnI2AgQgAyAFaiICIAcgBWsiAUEBcjYCBEHEKCABNgIAQdAoIAI2AgAMAQtBzCgoAgAgBkYEQEHAKCgCACAHaiICIAVJDQICQCACIAVrIgFBEE8EQCADIAUgCEEBcXJBAnI2AgQgAyAFaiIHIAFBAXI2AgQgAiADaiICIAE2AgAgAiACKAIEQX5xNgIEDAELIAMgCEEBcSACckECcjYCBCACIANqIgEgASgCBEEBcjYCBEEAIQdBACEBC0HMKCAHNgIAQcAoIAE2AgAMAQsgBigCBCICQQJxDQEgAkF4cSAHaiILIAVJDQEgCyAFayEMIAYoAgwhBAJAIAJB/wFNBEAgBigCCCIBIARGBEBBuChBuCgoAgBBfiACQQN2d3E2AgAMAgsgASAENgIMIAQgATYCCAwBCyAGKAIYIQoCQCAEIAZHBEAgBigCCCIBIAQ2AgwgBCABNgIIDAELAkAgBigCFCIBBH8gBkEUagUgBigCECIBRQ0BIAZBEGoLIQcDQCAHIQIgASIEQRRqIQcgASgCFCIBDQAgBEEQaiEHIAQoAhAiAQ0ACyACQQA2AgAMAQtBACEECyAKRQ0AAkAgBigCHCICQQJ0IgEoAugqIAZGBEAgAUHoKmogBDYCACAEDQFBvChBvCgoAgBBfiACd3E2AgAMAgsCQCAGIAooAhBGBEAgCiAENgIQDAELIAogBDYCFAsgBEUNAQsgBCAKNgIYIAYoAhAiAQRAIAQgATYCECABIAQ2AhgLIAYoAhQiAUUNACAEIAE2AhQgASAENgIYCyAMQQ9NBEAgAyAIQQFxIAtyQQJyNgIEIAMgC2oiASABKAIEQQFyNgIEDAELIAMgBSAIQQFxckECcjYCBCADIAVqIgIgDEEDcjYCBCADIAtqIgEgASgCBEEBcjYCBCACIAwQDgsgAyEBCyABCyIBBEAgAUEIagwBC0EAIAAQDCIDRQ0AGiADIAlBfEF4IAlBBGsoAgAiAUEDcRsgAUF4cWoiASAAIAAgAUsbEAQgCRANIAMLIgEEf0GQCCAANgIAQZQIIAE2AgAgAQVBAAsL6SkEGH8MfAV9An4CQCAARQ0AIAFBAEwNACACQQBMDQBBqCgtAABFBEBBqChBAToAAAtBASEKIAKtIAGtfiIzQYD0AyADIANBAEwbIgOtVgRAQQEgM7ogA7ijn5v8AiIDIANBAUwbIQoLAkACQEGAgAIQDyIQBEBBECAJIAlBAWtBwABPGyENIAFBAnQhDwNAIAAgDyAWbGohC0EAIQkDQCALIAlBAnRqIgMtAAMgCEsEQCAQIAMtAABBCXRBgOAHcWogAy0AAUEEdEGAH3FqIAMtAAJBAXZB/ABxaiIDIAMoAgBBAWo2AgALIAkgCmoiCSABSA0ACyAKIBZqIhYgAkgNAAtBACECQQAhCQNAIAIiCCAQIAlBAnRqIgAoAgAiF0EAR2ogACgCBCIYQQBHaiAAKAIIIhpBAEdqIAAoAgwiEkEAR2ohAiAJQQRqIglBgIACRw0ACwJAIAJFDQAgAkEMbBAMIQ8gAkECdCIVEAwhEwJAIA9FDQAgE0UNAEEAIQNBACEJA0AgECADQQJ0aigCACIABEAgDyAJQQxsaiIBIANBH3GzQwghBD2UOAIIIAEgA0EKdrNDCCEEPZQ4AgAgASADQQV2QR9xs0MIIQQ9lDgCBCATIAlBAnRqIACzOAIAIAlBAWohCQsgA0EBaiIDQYCAAkcNAAsgEBANQQEgDSACIAIgDUobIhQgFEEBTBsiEUEYbCIeEAwiDg0DQQAhCgwECyAPBEAgDxANCyATRQ0AIBMQDQsgEBANC0EAIQ9BoAhCADcDAEGgCCEKDAELQQAhAyMAQRBrIgEkACMAQSBrIgkkAEEAQgEgCUEYahAAIgAEf0GsKCAANgIAQX8FQQALBH9BfwUgCSkDGCE0IAlBADYCFCAJIDRCgJTr3AOAIjM3AwggCSA0IDNCgJTr3AN+fT4CECABIAkpAxA3AwggASAJKQMINwMAQQALGiAJQSBqJAAgASkDACEzIAFBEGokAEGwKCAzp0EBa603AwBBsChBsCgpAwBCrf7V5NSF/ajYAH5CAXwiMzcDACAOIA8gM0IhiKcgAm9BDGxqIgAoAgg2AgggDiAAKQIANwIAIA5CADcDEAJAIAJBA3QQDCIQBEAgDioCCLshJSAOKgIEuyEkIA4qAgC7ISMDQCAQIANBA3RqIA8gA0EMbGoiACoCBLsgJKEiIiAioiAAKgIAuyAjoSIiICKioCAAKgIIuyAloSIiICKioDkDACADQQFqIgMgAkcNAAsgFEECTwRAIAJBfnEhDSACQQFxIQsgCCAXQQBHaiAYQQBHaiAaQQBHakEBa0F/QQAgEhtGIQlBASEBA0BBACEKRAAAAAAAAAAAISJBACEDRAAAAAAAAAAAISNBACEMAkAgCUUEQANAIBAgA0EBciIAQQN0aisDACATIABBAnRqKgIAu6IgECADQQN0aisDACATIANBAnRqKgIAu6IgI6CgISMgA0ECaiEDIAxBAmoiDCANRw0ACyADIQogIyEiIAtFDQELIBAgCkEDdGorAwAgEyAKQQJ0aioCALuiICKgISMLAkAgI0QAAAAAAAAAAGRFBEBBsChBsCgpAwBCrf7V5NSF/ajYAH5CAXwiMzcDACAOIAFBGGxqIgMgDyAzQiGIpyACb0EMbGoiACgCCDYCCCADIAApAgA3AgAgA0IANwMQDAELQbAoQbAoKQMAQq3+1eTUhf2o2AB+QgF8IjM3AwAgI0QAACAAAAAAPqIgM0IhiKe3oiEiRAAAAAAAAAAAISNBACEDAkADQCAQIANBA3RqKwMAIBMgA0ECdGoqAgC7oiAjoCIjICJmDQEgA0EBaiIDIAJHDQALQQAhAwsgDiABQRhsaiIKIA8gA0EMbGoiACkCADcCACAKIAAoAggiADYCCCAKQgA3AxAgAL67ISUgCioCBLshJCAKKgIAuyEjQQAhAwNAIA8gA0EMbGoiACoCBLsgJKEiIiAioiAAKgIAuyAjoSIiICKioCAAKgIIuyAloSIiICKioCIiIBAgA0EDdGoiACsDAGZFBEAgACAiOQMACyADQQFqIgMgAkcNAAsLIBQgAUEBaiIBRw0ACwsgEBANDAELIBRBAkkNAEEBIQMDQEGwKEGwKCkDAEKt/tXk1IX9qNgAfkIBfCIzNwMAIA4gA0EYbGoiASAPIDNCIYinIAJvQQxsaiIAKAIINgIIIAEgACkCADcCACABQgA3AxAgFCADQQFqIgNHDQALCyAVEAwiGwRAIBUEQCAbQf8BIBX8CwALIBEQDyEKIBEQDyEAIBEQDyEBIBUQDCELAkACQAJAAkAgCkUNACAARQ0AIAENAQsgCgRAIAoQDQsgAARAIAAQDQsgAQ0BDAILIAsEQCACQXxxISEgAkEDcSEfIBFB+P///wdxIRAgEUEHcSEgIBFBAnQhHCAUQQhIIRUgCCAXQQBHaiAYQQBHaiAaQQBHaiASQQBHakEBa0EDSSEaQQAhFwNAIBxFIgNFBEAgAUEAIBz8CwALIANFBEAgAEEAIBz8CwALIANFBEAgCkEAIBz8CwALQQAhCUEAIQxBACEDAkAgFUUEQANAIA4gCUEYbGoiA0IANwO4ASADQgA3A6ABIANCADcDiAEgA0IANwNwIANCADcDWCADQgA3A0AgA0IANwMoIANCADcDECAJQQhqIQkgDEEIaiIMIBBHDQALIAkhAyAgRQ0BC0EAIQkDQCAOIANBGGxqQgA3AxAgA0EBaiEDIAlBAWoiCSAgRw0ACwtBACEdQQAhCANAIA8gCEEMbGoiAyoCCCExIAMqAgQhLyADKgIAITBDyvJJcSEyQQAhA0EAIQwDQCADIAwgLyAOIANBGGxqIgkqAgSTIi4gLpQgMCAJKgIAkyIuIC6UkiAxIAkqAgiTIi4gLpSSIi4gMl0bIQwgLiAyliEyIANBAWoiAyARRw0ACyALIAhBAnQiEmogMjgCACASIBtqIgMoAgAhCSADIAw2AgAgCiAMQQJ0Ig1qIgMgAyoCACASIBNqKgIAIi4gMJSSOAIAIAAgDWoiAyADKgIAIC4gL5SSOAIAIAEgDWoiAyADKgIAIC4gMZSSOAIAIA4gDEEYbGoiAyADKwMQIC67oDkDEEEBIB0gCSAMRxshHSAIQQFqIgggAkcNAAtBACEZA0ACQCAOIBlBGGxqIhgrAxAiIkQAAAAAAAAAAGQNAEF/IQxEAAAAAAAA8L8hI0EAIQhBACEJQQAhA0EAIRYCQCAaRQRAA0AgA0EDciISIANBAnIiDSADQQFyIgkgAyAMICMgCyADQQJ0aioCALsiJGMbICMgJKUiJCALIAlBAnRqKgIAuyIjYxsgIyAkpSIkIAsgDUECdGoqAgC7IiNjGyAjICSlIiQgCyASQQJ0aioCALsiI2MbIQwgIyAkpSEjIANBBGohAyAWQQRqIhYgIUcNAAsgAyEJIB9FDQELA0AgCSAMICMgCyAJQQJ0aioCALsiJGMbIQwgCUEBaiEJICMgJKUhIyAIQQFqIgggH0cNAAsLIAxBAEgNACAPIAxBDGxqIhIqAgAhLiATIAxBAnQiA2oqAgAhLwJAIBEgAyAbaiIIKAIAIg1NBEAgLiAvlCExIBIqAgggL5QhMCASKgIEIC+UIS4MAQsgCiANQQJ0IglqIgMgAyoCACAuIC+UIjGTOAIAIAAgCWoiAyADKgIAIBIqAgQgL5QiLpM4AgAgASAJaiIDIAMqAgAgEioCCCAvlCIwkzgCACAOIA1BGGxqIgMrAxAiI0QAAAAAAAAAAGUNACADICMgL7uhOQMQIBgrAxAhIgsgCCAZNgIAIAogGUECdCIIaiIDIAMqAgAgMZI4AgAgACAIaiIDIAMqAgAgLpI4AgAgASAIaiIDIAMqAgAgMJI4AgAgGCAiIC+7oDkDEEEBIR0LIBlBAWoiGSARRw0AC0EAIQMDQCAOIANBGGxqIgkrAxAiIkQAAAAAAAAAAGVFBEAgCSAKIANBAnQiCGoqAgBEAAAAAAAA8D8gIqO2Ii6UOAIAIAkgACAIaioCACAulDgCBCAJIAEgCGoqAgAgLpQ4AggLIANBAWoiAyARRw0ACyAdBEAgF0EBaiIXQQxHDQELCyAKEA0gACEKIAEhACALIQELIAoQDSAAEA0LIAEQDQsgGxANCyARQQNxIQFBACEMQQAhAwJAIBRBBE4EQCARQfz///8HcSEAQQAhCgNAIA4gA0EYbGoiAisDWCACKwNAIAIrAyggAisDECAooKCgoCEoIANBBGohAyAKQQRqIgogAEcNAAsgAUUNAQsDQCAOIANBGGxqKwMQICigISggA0EBaiEDIAxBAWoiDCABRw0ACwsgHhAMIQAgHgRAIAAgDiAe/AoAAAsgACEBIwBB0AFrIgskACALQgE3AwgCQCARQRhsIgNFDQAgC0EYNgIQIAtBGDYCFEECIQoDQCALQRBqIApBAnRqIgIgAkEEaygCACACQQhrKAIAQRhqaiICNgIAIApBAWohCiACIANJDQALAn8gA0EYayICQQBMBEBBASEKQQAMAQsgASACaiEIQQEhAkEBIQoDQAJ/IAJBA3FBA0YEQCABIAogC0EQahAFIAtBCGpBAhAGIApBAmoMAQsCQCALQRBqIgMgCkEBayICQQJ0aigCACAIIAFrTwRAIAEgC0EIaiAKQQAgAxAHDAELIAEgCiALQRBqEAULIApBAUYEQCALQQhqQQEQCEEADAELIAtBCGogAhAIQQELIQogCyALKAIIQQFyIgI2AgggAUEYaiIBIAhJDQALIAsoAgxBAEcLIQIgASALQQhqIApBACALQRBqEAcCQCAKQQFHDQAgCygCCEEBRw0AIAJFDQELA0ACfyAKQQFMBEAgC0EIaiICIAIQCSICEAYgAiAKagwBCyALQQhqIglBAhAIIAsgCygCCEEHczYCCCAJQQEQBiABQRhrIgIgC0EQaiIIIApBAmsiA0ECdGooAgBrIAkgCkEBa0EBIAgQByAJQQEQCCALIAsoAghBAXI2AgggAiAJIANBASAIEAcgAwshCiABQRhrIQEgCygCDCEDIAsoAgghAiAKQQFHDQAgAkEBRw0AIAMNAAsLIAtB0AFqJAAgBCAEokQAAAAAAAAIQKIhJEEAIQogEUEwbBAMIQJBACEIA0ACQCAAIAhBGGxqIgErAxAiLEQAAAAAAAAAAGUNACABKgIAIi67IikgASoCBCIvuyIqIAEqAggiMLsiLaWlIiMgKSAqIC2kpCIioCIERAAAAAAAAOA/oiEnAnwgIiAjYQRARAAAAAAAAAAAISZEAAAAAAAAAAAMAQsgIyAioSIiRAAAAAAAAABAIAShIAQgJ0QAAAAAAADgP2QboyEmAnwgKiAtoSAio0QAAAAAAAAYQEQAAAAAAAAAACAvIDBdG6AgIyApYQ0AGiAtICmhICKjRAAAAAAAAABAoCAjICphDQAaICkgKqEgIqNEAAAAAAAAEECgC0RVVVVVVVXFP6ILISVBACEJIApBAEoEQANAAkAgKiACIAlBMGxqIgEqAgQiMrsiI6EiBCAEoiApIAEqAgC7IgShIiIgIqKgIC0gASoCCCIxuyIroSIiICKioCAkZUUEQCAmIAErAyChmSAFZg0BICcgASsDKKGZIAZmDQFEAAAAAAAA8D8gJSABKwMYoZkiIqEgIiAiRAAAAAAAAOA/ZBsgB2YNAQsgASsDECIiICygIiVEAAAAAAAAAABlRQRAIAEgIiAroiAsIC2ioCAloyIrtiIxOAIIIAEgIiAjoiAsICqioCAloyIjtiIyOAIEIAEgIiAEoiAsICmioCAloyIEtjgCAAsgASAlOQMQIAQgIyArpaUiJyAEICMgK6SkIiagIiJEAAAAAAAA4D+iISUCfCAmICdhBEBEAAAAAAAAAAAhIkQAAAAAAAAAAAwBCyAnICahIiZEAAAAAAAAAEAgIqEgIiAlRAAAAAAAAOA/ZBujISICfEQAAAAAAAAYQEQAAAAAAAAAACAxIDJeGyAjICuhICajoCAEICdhDQAaICsgBKEgJqNEAAAAAAAAAECgICMgJ2ENABogBCAjoSAmo0QAAAAAAAAQQKALRFVVVVVVVcU/ogshBCABICU5AyggASAiOQMgIAEgBDkDGAwDCyAJQQFqIgkgCkcNAAsLIAIgCkEwbGoiASAnOQMoIAEgJjkDICABICU5AxggASAsOQMQIAEgMDgCCCABIC84AgQgASAuOAIAIApBAWohCgsgCEEBaiIIIBFHDQALIAAQDQJAIApBAEwiCw0AIChEAAAAAAAAAABkRQRAIApBB3EhA0EAIQFBACEJIApBCE8EQCAKQfj///8HcSEAQQAhCANAIAIgCUEwbGoiDUIANwPgAiANQgA3A7ACIA1CADcDgAIgDUIANwPQASANQgA3A6ABIA1CADcDcCANQgA3A0AgDUIANwMQIAlBCGohCSAIQQhqIgggAEcNAAsgA0UNAgsDQCACIAlBMGxqQgA3AxAgCUEBaiEJIAFBAWoiASADRw0ACwwBC0EAIQkgCkEBRwRAIApBAXEhA0QAAAAAAADwPyAooyEEIApB/v///wdxIQBBACEBA0AgAiAJQTBsaiIIIAgrAxAgBKI5AxAgCCAIKwNAIASiOQNAIAlBAmohCSABQQJqIgEgAEcNAAsgA0UNAQsgAiAJQTBsaiIAIAArAxAgKKM5AxALIA8QDSATEA0gDhANQQAhA0GgCEHAACAKIApBwABOGyIAtzkDAEGgCCEKIAtFBEADQCACIANBMGxqIgEqAgghLyABKgIEITAgASoCACEuIAErAxghBSABKwMoIQQgA0EGdCIIIAErAyA5A9gIIAggBDkD0AggCCAFOQPACCAIIDC7IgYgLrsiBaAgL7siBKBEVVVVVVVV1T+iOQPICCAIIAREAAAAAAAA8D+kRAAAAAAAAAAApUQAAAAAAOBvQKI5A7gIIAggBkQAAAAAAADwP6REAAAAAAAAAAClRAAAAAAA4G9AojkDsAggCCAFRAAAAAAAAPA/pEQAAAAAAAAAAKVEAAAAAADgb0CiOQOoCCAIQeAIaiABKwMQOQMAIANBAWoiAyAARw0ACwsgAiEPCyAPEA0LIAoLIAECfEEBQX9BACAAKwMQIgIgASsDECIDZBsgAiADYxsLhwQBAn8gAkGABE8EQCACBEAgACABIAL8CgAACw8LIAAgAmohAwJAIAAgAXNBA3FFBEACQCAAQQNxRQRAIAAhAgwBCyACRQRAIAAhAgwBCyAAIQIDQCACIAEtAAA6AAAgAUEBaiEBIAJBAWoiAkEDcUUNASACIANJDQALCyADQXxxIQACQCADQcAASQ0AIAIgAEFAaiIESw0AA0AgAiABKAIANgIAIAIgASgCBDYCBCACIAEoAgg2AgggAiABKAIMNgIMIAIgASgCEDYCECACIAEoAhQ2AhQgAiABKAIYNgIYIAIgASgCHDYCHCACIAEoAiA2AiAgAiABKAIkNgIkIAIgASgCKDYCKCACIAEoAiw2AiwgAiABKAIwNgIwIAIgASgCNDYCNCACIAEoAjg2AjggAiABKAI8NgI8IAFBQGshASACQUBrIgIgBE0NAAsLIAAgAk0NAQNAIAIgASgCADYCACABQQRqIQEgAkEEaiICIABJDQALDAELIANBBEkEQCAAIQIMAQsgAkEESQRAIAAhAgwBCyADQQRrIQQgACECA0AgAiABLQAAOgAAIAIgAS0AAToAASACIAEtAAI6AAIgAiABLQADOgADIAFBBGohASACQQRqIgIgBE0NAAsLIAIgA0kEQANAIAIgAS0AADoAACABQQFqIQEgAkEBaiICIANHDQALCwuiAQEFfyMAQfABayIEJAAgBCAANgIAQQEhBQJAIAFBAkgNACAAIQMDQCAAIANBGGsiAyACIAFBAmsiB0ECdGooAgBrIgZBARALQQBOBEAgACADQQEQC0EATg0CCyAEIAVBAnRqIAYgAyAGIANBARALQQBOIgYbIgM2AgAgBUEBaiEFIAFBAWsgByAGGyIBQQFKDQALCyAEIAUQCiAEQfABaiQAC0sBAn8gACgCBCECIAACfyABQR9NBEAgACgCACEDIAIMAQsgAUEgayEBIAIhA0EACyICIAF2NgIEIAAgAkEgIAFrdCADIAF2cjYCAAu4AgEFfyMAQfABayIGJAAgBiABKAIAIgU2AugBIAEoAgQhASAGIAA2AgAgBiABNgLsASADRSEIAkACQAJAAkAgBUEBRwRAIAAhBUEBIQMMAQsgACEFQQEhAyABDQAMAQsDQCAFIAQgAkECdGoiBygCAGsiASAAQQEQC0EATA0BIAhBf3MhCUEBIQgCQCAJIAJBAkhyQQFxRQRAIAdBCGsoAgAhByAFQRhrIgkgAUEBEAtBAE4NASAJIAdrIAFBARALQQBODQELIAYgA0ECdGogATYCACAGQegBaiIFIAUQCSIFEAYgA0EBaiEDIAIgBWohAiAGKALsASEHIAEhBSAGKALoAUEBRw0BIAcNAQwDCwsgBSEBDAELIAUhASAIRQ0BCyAGIAMQCiABIAIgBBAFCyAGQfABaiQAC0gBAn8CfyABQR9NBEAgACgCACECIABBBGoMAQsgAUEgayEBIAALKAIAIQMgACACIAF0NgIAIAAgAyABdCACQSAgAWt2cjYCBAszAQF/IAAoAgBBAWsiAWhBACABGyIBBH8gAQUgACgCBCIAaEEAIAAbIgBBIHJBACAAGwsLkwEBBn9BGCECIwBBgAJrIgUkACABQQJOBEAgACABQQJ0aiIHIAU2AgADQCAHKAIAIAAoAgBBgAIgAiACQYACTxsiBBAEQQAhAwNAIAAgA0ECdGoiBigCACAAIANBAWoiA0ECdGooAgAgBBAEIAYgBigCACAEajYCACABIANHDQALIAIgBGsiAg0ACwsgBUGAAmokAAsLACAAIAEgAhECAAvFJwELfyMAQRBrIgokAAJAAkACQAJAAkACQAJAAkACQAJAIABB9AFNBEBBuCgoAgAiBEEQIABBC2pB+ANxIABBC0kbIgZBA3YiAHYiAUEDcQRAAkAgAUF/c0EBcSAAaiIDQQN0IgFB4ChqIgAgASgC6CgiAigCCCIFRgRAQbgoIARBfiADd3E2AgAMAQsgBSAANgIMIAAgBTYCCAsgAkEIaiEAIAIgAUEDcjYCBCABIAJqIgEgASgCBEEBcjYCBAwLCyAGQcAoKAIAIghNDQEgAQRAAkBBAiAAdCICQQAgAmtyIAEgAHRxaCIDQQN0IgFB4ChqIgIgASgC6CgiACgCCCIFRgRAQbgoIARBfiADd3EiBDYCAAwBCyAFIAI2AgwgAiAFNgIICyAAIAZBA3I2AgQgACAGaiIHIAEgBmsiBUEBcjYCBCAAIAFqIAU2AgAgCARAIAhBeHFB4ChqIQFBzCgoAgAhAgJ/IARBASAIQQN2dCIDcUUEQEG4KCADIARyNgIAIAEMAQsgASgCCAshAyABIAI2AgggAyACNgIMIAIgATYCDCACIAM2AggLIABBCGohAEHMKCAHNgIAQcAoIAU2AgAMCwtBvCgoAgAiC0UNASALaEECdCgC6CoiASgCBEF4cSAGayEDIAEhAgNAAkAgASgCECIARQRAIAEoAhQiAEUNAQsgACgCBEF4cSAGayIBIAMgASADSSIBGyEDIAAgAiABGyECIAAhAQwBCwsgAigCGCEJIAIgAigCDCIARwRAIAIoAggiASAANgIMIAAgATYCCAwKCyACKAIUIgEEfyACQRRqBSACKAIQIgFFDQMgAkEQagshBQNAIAUhByABIgBBFGohBSAAKAIUIgENACAAQRBqIQUgACgCECIBDQALIAdBADYCAAwJC0F/IQYgAEG/f0sNACAAQQtqIgFBeHEhBkG8KCgCACIHRQ0AQR8hCEEAIAZrIQMgAEH0//8HTQRAIAZBJiABQQh2ZyIAa3ZBAXEgAEEBdGtBPmohCAsCQAJAAkAgCEECdCgC6CoiAUUEQEEAIQAMAQtBACEAIAZBGSAIQQF2a0EAIAhBH0cbdCECA0ACQCABKAIEQXhxIAZrIgQgA08NACABIQUgBCIDDQBBACEDIAEhAAwDCyAAIAEoAhQiBCAEIAEgAkEddkEEcWooAhAiAUYbIAAgBBshACACQQF0IQIgAQ0ACwsgACAFckUEQEEAIQVBAiAIdCIAQQAgAGtyIAdxIgBFDQMgAGhBAnQoAugqIQALIABFDQELA0AgACgCBEF4cSAGayICIANJIQEgAiADIAEbIQMgACAFIAEbIQUgACgCECIBBH8gAQUgACgCFAsiAA0ACwsgBUUNACADQcAoKAIAIAZrTw0AIAUoAhghCCAFIAUoAgwiAEcEQCAFKAIIIgEgADYCDCAAIAE2AggMCAsgBSgCFCIBBH8gBUEUagUgBSgCECIBRQ0DIAVBEGoLIQIDQCACIQQgASIAQRRqIQIgACgCFCIBDQAgAEEQaiECIAAoAhAiAQ0ACyAEQQA2AgAMBwsgBkHAKCgCACIFTQRAQcwoKAIAIQACQCAFIAZrIgFBEE8EQCAAIAZqIgIgAUEBcjYCBCAAIAVqIAE2AgAgACAGQQNyNgIEDAELIAAgBUEDcjYCBCAAIAVqIgEgASgCBEEBcjYCBEEAIQFBACECC0HAKCABNgIAQcwoIAI2AgAgAEEIaiEADAkLIAZBxCgoAgAiAkkEQEHEKCACIAZrIgE2AgBB0ChB0CgoAgAiACAGaiICNgIAIAIgAUEBcjYCBCAAIAZBA3I2AgQgAEEIaiEADAkLQQAhACAGQS9qIgMCf0GQLCgCAARAQZgsKAIADAELQZwsQn83AgBBlCxCgKCAgICABDcCAEGQLCAKQQxqQXBxQdiq1aoFczYCAEGkLEEANgIAQfQrQQA2AgBBgCALIgFqIgRBACABayIHcSIBIAZNDQhB8CsoAgAiBQRAQegrKAIAIgggAWoiCSAITQ0JIAUgCUkNCQsCQEH0Ky0AAEEEcUUEQAJAAkACQAJAQdAoKAIAIgUEQEH4KyEAA0AgACgCACIIIAVNBEAgBSAIIAAoAgRqSQ0DCyAAKAIIIgANAAsLQQAQECICQX9GDQMgASEEQZQsKAIAIgBBAWsiBSACcQRAIAEgAmsgAiAFakEAIABrcWohBAsgBCAGTQ0DQfArKAIAIgAEQEHoKygCACIFIARqIgcgBU0NBCAAIAdJDQQLIAQQECIAIAJHDQEMBQsgBCACayAHcSIEEBAiAiAAKAIAIAAoAgRqRg0BIAIhAAsgAEF/Rg0BIAZBMGogBE0EQCAAIQIMBAtBmCwoAgAiAiADIARrakEAIAJrcSICEBBBf0YNASACIARqIQQgACECDAMLIAJBf0cNAgtB9CtB9CsoAgBBBHI2AgALIAEQECECQQAQECEAIAJBf0YNBSAAQX9GDQUgACACTQ0FIAAgAmsiBCAGQShqTQ0FC0HoK0HoKygCACAEaiIANgIAQewrKAIAIABJBEBB7CsgADYCAAsCQEHQKCgCACIDBEBB+CshAANAIAIgACgCACIBIAAoAgQiBWpGDQIgACgCCCIADQALDAQLQcgoKAIAIgBBACAAIAJNG0UEQEHIKCACNgIAC0EAIQBB/CsgBDYCAEH4KyACNgIAQdgoQX82AgBB3ChBkCwoAgA2AgBBhCxBADYCAANAIABBA3QiASABQeAoaiIFNgLoKCABIAU2AuwoIABBAWoiAEEgRw0AC0HEKCAEQShrIgBBeCACa0EHcSIBayIFNgIAQdAoIAEgAmoiATYCACABIAVBAXI2AgQgACACakEoNgIEQdQoQaAsKAIANgIADAQLIAIgA00NAiABIANLDQIgACgCDEEIcQ0CIAAgBCAFajYCBEHQKCADQXggA2tBB3EiAGoiATYCAEHEKEHEKCgCACAEaiICIABrIgA2AgAgASAAQQFyNgIEIAIgA2pBKDYCBEHUKEGgLCgCADYCAAwDC0EAIQAMBgtBACEADAQLQcgoKAIAIAJLBEBByCggAjYCAAsgAiAEaiEFQfgrIQACQANAIAUgACgCACIBRwRAIAAoAggiAA0BDAILCyAALQAMQQhxRQ0DC0H4KyEAA0ACQCAAKAIAIgEgA00EQCADIAEgACgCBGoiBUkNAQsgACgCCCEADAELC0HEKCAEQShrIgBBeCACa0EHcSIBayIHNgIAQdAoIAEgAmoiATYCACABIAdBAXI2AgQgACACakEoNgIEQdQoQaAsKAIANgIAIAMgBUEnIAVrQQdxakEvayIAIAAgA0EQakkbIgFBGzYCBCABQYAsKQIANwIQIAFB+CspAgA3AghBgCwgAUEIajYCAEH8KyAENgIAQfgrIAI2AgBBhCxBADYCACABQRhqIQADQCAAQQc2AgQgAEEIaiECIABBBGohACACIAVJDQALIAEgA0YNACABIAEoAgRBfnE2AgQgAyABIANrIgJBAXI2AgQgASACNgIAAn8gAkH/AU0EQCACQfgBcUHgKGohAAJ/QbgoKAIAIgFBASACQQN2dCICcUUEQEG4KCABIAJyNgIAIAAMAQsgACgCCAshASAAIAM2AgggASADNgIMQQwhAkEIDAELQR8hACACQf///wdNBEAgAkEmIAJBCHZnIgBrdkEBcSAAQQF0ckE+cyEACyADIAA2AhwgA0IANwIQIABBAnRB6CpqIQECQAJAQbwoKAIAIgVBASAAdCIEcUUEQEG8KCAEIAVyNgIAIAEgAzYCAAwBCyACQRkgAEEBdmtBACAAQR9HG3QhACABKAIAIQUDQCAFIgEoAgRBeHEgAkYNAiAAQR12IQUgAEEBdCEAIAEgBUEEcWoiBCgCECIFDQALIAQgAzYCEAsgAyABNgIYQQghAiADIgEhAEEMDAELIAEoAggiACADNgIMIAEgAzYCCCADIAA2AghBACEAQRghAkEMCyADaiABNgIAIAIgA2ogADYCAAtBxCgoAgAiACAGTQ0AQcQoIAAgBmsiATYCAEHQKEHQKCgCACIAIAZqIgI2AgAgAiABQQFyNgIEIAAgBkEDcjYCBCAAQQhqIQAMBAtBrChBMDYCAEEAIQAMAwsgACACNgIAIAAgACgCBCAEajYCBCACQXggAmtBB3FqIgggBkEDcjYCBCABQXggAWtBB3FqIgQgBiAIaiIDayEHAkBB0CgoAgAgBEYEQEHQKCADNgIAQcQoQcQoKAIAIAdqIgA2AgAgAyAAQQFyNgIEDAELQcwoKAIAIARGBEBBzCggAzYCAEHAKEHAKCgCACAHaiIANgIAIAMgAEEBcjYCBCAAIANqIAA2AgAMAQsgBCgCBCIAQQNxQQFGBEAgAEF4cSEJIAQoAgwhAgJAIABB/wFNBEAgBCgCCCIBIAJGBEBBuChBuCgoAgBBfiAAQQN2d3E2AgAMAgsgASACNgIMIAIgATYCCAwBCyAEKAIYIQYCQCACIARHBEAgBCgCCCIAIAI2AgwgAiAANgIIDAELAkAgBCgCFCIABH8gBEEUagUgBCgCECIARQ0BIARBEGoLIQEDQCABIQUgACICQRRqIQEgACgCFCIADQAgAkEQaiEBIAIoAhAiAA0ACyAFQQA2AgAMAQtBACECCyAGRQ0AAkAgBCgCHCIAQQJ0IgEoAugqIARGBEAgAUHoKmogAjYCACACDQFBvChBvCgoAgBBfiAAd3E2AgAMAgsCQCAEIAYoAhBGBEAgBiACNgIQDAELIAYgAjYCFAsgAkUNAQsgAiAGNgIYIAQoAhAiAARAIAIgADYCECAAIAI2AhgLIAQoAhQiAEUNACACIAA2AhQgACACNgIYCyAHIAlqIQcgBCAJaiIEKAIEIQALIAQgAEF+cTYCBCADIAdBAXI2AgQgAyAHaiAHNgIAIAdB/wFNBEAgB0H4AXFB4ChqIQACf0G4KCgCACIBQQEgB0EDdnQiAnFFBEBBuCggASACcjYCACAADAELIAAoAggLIQEgACADNgIIIAEgAzYCDCADIAA2AgwgAyABNgIIDAELQR8hAiAHQf///wdNBEAgB0EmIAdBCHZnIgBrdkEBcSAAQQF0ckE+cyECCyADIAI2AhwgA0IANwIQIAJBAnRB6CpqIQACQAJAQbwoKAIAIgFBASACdCIFcUUEQEG8KCABIAVyNgIAIAAgAzYCAAwBCyAHQRkgAkEBdmtBACACQR9HG3QhAiAAKAIAIQEDQCABIgAoAgRBeHEgB0YNAiACQR12IQEgAkEBdCECIAAgAUEEcWoiBSgCECIBDQALIAUgAzYCEAsgAyAANgIYIAMgAzYCDCADIAM2AggMAQsgACgCCCIBIAM2AgwgACADNgIIIANBADYCGCADIAA2AgwgAyABNgIICyAIQQhqIQAMAgsCQCAIRQ0AAkAgBSgCHCIBQQJ0IgIoAugqIAVGBEAgAkHoKmogADYCACAADQFBvCggB0F+IAF3cSIHNgIADAILAkAgBSAIKAIQRgRAIAggADYCEAwBCyAIIAA2AhQLIABFDQELIAAgCDYCGCAFKAIQIgEEQCAAIAE2AhAgASAANgIYCyAFKAIUIgFFDQAgACABNgIUIAEgADYCGAsCQCADQQ9NBEAgBSADIAZqIgBBA3I2AgQgACAFaiIAIAAoAgRBAXI2AgQMAQsgBSAGQQNyNgIEIAUgBmoiBCADQQFyNgIEIAMgBGogAzYCACADQf8BTQRAIANB+AFxQeAoaiEAAn9BuCgoAgAiAUEBIANBA3Z0IgJxRQRAQbgoIAEgAnI2AgAgAAwBCyAAKAIICyEBIAAgBDYCCCABIAQ2AgwgBCAANgIMIAQgATYCCAwBC0EfIQAgA0H///8HTQRAIANBJiADQQh2ZyIAa3ZBAXEgAEEBdHJBPnMhAAsgBCAANgIcIARCADcCECAAQQJ0QegqaiEBAkACQCAHQQEgAHQiAnFFBEBBvCggAiAHcjYCACABIAQ2AgAgBCABNgIYDAELIANBGSAAQQF2a0EAIABBH0cbdCEAIAEoAgAhAQNAIAEiAigCBEF4cSADRg0CIABBHXYhASAAQQF0IQAgAiABQQRxaiIHKAIQIgENAAsgByAENgIQIAQgAjYCGAsgBCAENgIMIAQgBDYCCAwBCyACKAIIIgAgBDYCDCACIAQ2AgggBEEANgIYIAQgAjYCDCAEIAA2AggLIAVBCGohAAwBCwJAIAlFDQACQCACKAIcIgFBAnQiBSgC6CogAkYEQCAFQegqaiAANgIAIAANAUG8KCALQX4gAXdxNgIADAILAkAgAiAJKAIQRgRAIAkgADYCEAwBCyAJIAA2AhQLIABFDQELIAAgCTYCGCACKAIQIgEEQCAAIAE2AhAgASAANgIYCyACKAIUIgFFDQAgACABNgIUIAEgADYCGAsCQCADQQ9NBEAgAiADIAZqIgBBA3I2AgQgACACaiIAIAAoAgRBAXI2AgQMAQsgAiAGQQNyNgIEIAIgBmoiBSADQQFyNgIEIAMgBWogAzYCACAIBEAgCEF4cUHgKGohAEHMKCgCACEBAn9BASAIQQN2dCIHIARxRQRAQbgoIAQgB3I2AgAgAAwBCyAAKAIICyEEIAAgATYCCCAEIAE2AgwgASAANgIMIAEgBDYCCAtBzCggBTYCAEHAKCADNgIACyACQQhqIQALIApBEGokACAAC98LAQh/AkAgAEUNACAAQQhrIgMgAEEEaygCACICQXhxIgBqIQUCQCACQQFxDQAgAkECcUUNASADIAMoAgAiBGsiA0HIKCgCAEkNASAAIARqIQACQAJAAkBBzCgoAgAgA0cEQCADKAIMIQEgBEH/AU0EQCABIAMoAggiAkcNAkG4KEG4KCgCAEF+IARBA3Z3cTYCAAwFCyADKAIYIQcgASADRwRAIAMoAggiAiABNgIMIAEgAjYCCAwECyADKAIUIgIEfyADQRRqBSADKAIQIgJFDQMgA0EQagshBANAIAQhBiACIgFBFGohBCABKAIUIgINACABQRBqIQQgASgCECICDQALIAZBADYCAAwDCyAFKAIEIgJBA3FBA0cNA0HAKCAANgIAIAUgAkF+cTYCBCADIABBAXI2AgQgBSAANgIADwsgAiABNgIMIAEgAjYCCAwCC0EAIQELIAdFDQACQCADKAIcIgRBAnQiAigC6CogA0YEQCACQegqaiABNgIAIAENAUG8KEG8KCgCAEF+IAR3cTYCAAwCCwJAIAMgBygCEEYEQCAHIAE2AhAMAQsgByABNgIUCyABRQ0BCyABIAc2AhggAygCECICBEAgASACNgIQIAIgATYCGAsgAygCFCICRQ0AIAEgAjYCFCACIAE2AhgLIAMgBU8NACAFKAIEIgRBAXFFDQACQAJAAkACQCAEQQJxRQRAQdAoKAIAIAVGBEBB0CggAzYCAEHEKEHEKCgCACAAaiIANgIAIAMgAEEBcjYCBCADQcwoKAIARw0GQcAoQQA2AgBBzChBADYCAA8LQcwoKAIAIgcgBUYEQEHMKCADNgIAQcAoQcAoKAIAIABqIgA2AgAgAyAAQQFyNgIEIAAgA2ogADYCAA8LIARBeHEgAGohACAFKAIMIQEgBEH/AU0EQCAFKAIIIgIgAUYEQEG4KEG4KCgCAEF+IARBA3Z3cTYCAAwFCyACIAE2AgwgASACNgIIDAQLIAUoAhghCCABIAVHBEAgBSgCCCICIAE2AgwgASACNgIIDAMLIAUoAhQiAgR/IAVBFGoFIAUoAhAiAkUNAiAFQRBqCyEEA0AgBCEGIAIiAUEUaiEEIAEoAhQiAg0AIAFBEGohBCABKAIQIgINAAsgBkEANgIADAILIAUgBEF+cTYCBCADIABBAXI2AgQgACADaiAANgIADAMLQQAhAQsgCEUNAAJAIAUoAhwiBEECdCICKALoKiAFRgRAIAJB6CpqIAE2AgAgAQ0BQbwoQbwoKAIAQX4gBHdxNgIADAILAkAgBSAIKAIQRgRAIAggATYCEAwBCyAIIAE2AhQLIAFFDQELIAEgCDYCGCAFKAIQIgIEQCABIAI2AhAgAiABNgIYCyAFKAIUIgJFDQAgASACNgIUIAIgATYCGAsgAyAAQQFyNgIEIAAgA2ogADYCACADIAdHDQBBwCggADYCAA8LIABB/wFNBEAgAEH4AXFB4ChqIQICf0G4KCgCACIEQQEgAEEDdnQiAHFFBEBBuCggACAEcjYCACACDAELIAIoAggLIQAgAiADNgIIIAAgAzYCDCADIAI2AgwgAyAANgIIDwtBHyEBIABB////B00EQCAAQSYgAEEIdmciAmt2QQFxIAJBAXRyQT5zIQELIAMgATYCHCADQgA3AhAgAUECdEHoKmohBAJ/AkACf0G8KCgCACIGQQEgAXQiAnFFBEBBvCggAiAGcjYCACAEIAM2AgBBGCEBQQgMAQsgAEEZIAFBAXZrQQAgAUEfRxt0IQEgBCgCACEEA0AgBCICKAIEQXhxIABGDQIgAUEddiEEIAFBAXQhASACIARBBHFqIgYoAhAiBA0ACyAGIAM2AhBBGCEBIAIhBEEICyEAIAMiAgwBCyACKAIIIgQgAzYCDCACIAM2AghBGCEAQQghAUEACyEGIAEgA2ogBDYCACADIAI2AgwgACADaiAGNgIAQdgoQdgoKAIAQQFrIgBBfyAAGzYCAAsLjQsBB38gACABaiEFAkACQCAAKAIEIgJBAXENACACQQJxRQ0BIAAoAgAiAiABaiEBAkACQAJAIAAgAmsiAEHMKCgCAEcEQCAAKAIMIQMgAkH/AU0EQCADIAAoAggiBEcNAkG4KEG4KCgCAEF+IAJBA3Z3cTYCAAwFCyAAKAIYIQYgACADRwRAIAAoAggiAiADNgIMIAMgAjYCCAwECyAAKAIUIgQEfyAAQRRqBSAAKAIQIgRFDQMgAEEQagshAgNAIAIhByAEIgNBFGohAiADKAIUIgQNACADQRBqIQIgAygCECIEDQALIAdBADYCAAwDCyAFKAIEIgJBA3FBA0cNA0HAKCABNgIAIAUgAkF+cTYCBCAAIAFBAXI2AgQgBSABNgIADwsgBCADNgIMIAMgBDYCCAwCC0EAIQMLIAZFDQACQCAAKAIcIgJBAnQiBCgC6CogAEYEQCAEQegqaiADNgIAIAMNAUG8KEG8KCgCAEF+IAJ3cTYCAAwCCwJAIAAgBigCEEYEQCAGIAM2AhAMAQsgBiADNgIUCyADRQ0BCyADIAY2AhggACgCECICBEAgAyACNgIQIAIgAzYCGAsgACgCFCICRQ0AIAMgAjYCFCACIAM2AhgLAkACQAJAAkAgBSgCBCICQQJxRQRAQdAoKAIAIAVGBEBB0CggADYCAEHEKEHEKCgCACABaiIBNgIAIAAgAUEBcjYCBCAAQcwoKAIARw0GQcAoQQA2AgBBzChBADYCAA8LQcwoKAIAIgggBUYEQEHMKCAANgIAQcAoQcAoKAIAIAFqIgE2AgAgACABQQFyNgIEIAAgAWogATYCAA8LIAJBeHEgAWohASAFKAIMIQMgAkH/AU0EQCAFKAIIIgQgA0YEQEG4KEG4KCgCAEF+IAJBA3Z3cTYCAAwFCyAEIAM2AgwgAyAENgIIDAQLIAUoAhghBiADIAVHBEAgBSgCCCICIAM2AgwgAyACNgIIDAMLIAUoAhQiBAR/IAVBFGoFIAUoAhAiBEUNAiAFQRBqCyECA0AgAiEHIAQiA0EUaiECIAMoAhQiBA0AIANBEGohAiADKAIQIgQNAAsgB0EANgIADAILIAUgAkF+cTYCBCAAIAFBAXI2AgQgACABaiABNgIADAMLQQAhAwsgBkUNAAJAIAUoAhwiAkECdCIEKALoKiAFRgRAIARB6CpqIAM2AgAgAw0BQbwoQbwoKAIAQX4gAndxNgIADAILAkAgBSAGKAIQRgRAIAYgAzYCEAwBCyAGIAM2AhQLIANFDQELIAMgBjYCGCAFKAIQIgIEQCADIAI2AhAgAiADNgIYCyAFKAIUIgJFDQAgAyACNgIUIAIgAzYCGAsgACABQQFyNgIEIAAgAWogATYCACAAIAhHDQBBwCggATYCAA8LIAFB/wFNBEAgAUH4AXFB4ChqIQICf0G4KCgCACIDQQEgAUEDdnQiAXFFBEBBuCggASADcjYCACACDAELIAIoAggLIQEgAiAANgIIIAEgADYCDCAAIAI2AgwgACABNgIIDwtBHyEDIAFB////B00EQCABQSYgAUEIdmciAmt2QQFxIAJBAXRyQT5zIQMLIAAgAzYCHCAAQgA3AhAgA0ECdEHoKmohAgJAAkBBvCgoAgAiBEEBIAN0IgdxRQRAQbwoIAQgB3I2AgAgAiAANgIAIAAgAjYCGAwBCyABQRkgA0EBdmtBACADQR9HG3QhAyACKAIAIQIDQCACIgQoAgRBeHEgAUYNAiADQR12IQIgA0EBdCEDIAQgAkEEcWoiBygCECICDQALIAcgADYCECAAIAQ2AhgLIAAgADYCDCAAIAA2AggPCyAEKAIIIgEgADYCDCAEIAA2AgggAEEANgIYIAAgBDYCDCAAIAE2AggLC6IDAgN/AX4CQAJ/QQAgAEUNABogAK1CAoYiBKciAiAAQQRyQYCABEkNABpBfyACIARCIIinGwsiABAMIgJFDQAgAkEEay0AAEEDcUUNAAJAIABFDQAgAkEAOgAAIAAgAmoiAUEBa0EAOgAAIABBA0kNACACQQA6AAIgAkEAOgABIAFBA2tBADoAACABQQJrQQA6AAAgAEEHSQ0AIAJBADoAAyABQQRrQQA6AAAgAEEJSQ0AIAJBACACa0EDcSIBaiIDQQA2AgAgAyAAIAFrQXxxIgBqIgFBBGtBADYCACAAQQlJDQAgA0EANgIIIANBADYCBCABQQhrQQA2AgAgAUEMa0EANgIAIABBGUkNACADQQA2AhggA0EANgIUIANBADYCECADQQA2AgwgAUEQa0EANgIAIAFBFGtBADYCACABQRhrQQA2AgAgAUEca0EANgIAIAAgA0EEcUEYciIAayIBQSBJDQAgACADaiEAA0AgAEIANwMYIABCADcDECAAQgA3AwggAEIANwMAIABBIGohACABQSBrIgFBH0sNAAsLCyACC04CAX8BfgJAQYAIKAIAIgGtIACtQgd8Qvj///8fg3wiAkL/////D1gEQCACpyIAPwBBEHRNDQELQawoQTA2AgBBfw8LQYAIIAA2AgAgAQsGACAAJAALBAAjAAsLCgEAQYAICwMwFgE=";

function decodeBase64(b64) {
  if (typeof atob === "function") {
    const binary = atob(b64);
    const bytes = new Uint8Array(binary.length);
    for (let i = 0; i < binary.length; i++) bytes[i] = binary.charCodeAt(i);
    return bytes;
  }
  if (typeof Buffer !== "undefined") return new Uint8Array(Buffer.from(b64, "base64"));
  throw new Error("No base64 decoder available");
}

let extractExports = null;
let extractMemory = null;
let _wasmPromise = null;

let _sharedCanvas = null;
function getSharedCanvas() {
  if (_sharedCanvas) return _sharedCanvas;
  _sharedCanvas = document.createElement("canvas");
  return _sharedCanvas;
}

let _sharedCtx2D = null;
function getShared2DContext() {
  if (_sharedCtx2D) return _sharedCtx2D;
  const canvas = getSharedCanvas();
  _sharedCtx2D = canvas.getContext("2d", { willReadFrequently: true });
  return _sharedCtx2D;
}

const ENV_MEMORY = new WebAssembly.Memory({ initial: 256, maximum: 2048 });
const ENV_TABLE = new WebAssembly.Table({ initial: 0, element: "anyfunc" });

function resolveWasmUrl(urlOrRelative) {
  if (typeof urlOrRelative === "string" && urlOrRelative.includes("://")) {
    return urlOrRelative;
  }
  return new URL(urlOrRelative, import.meta.url).href;
}

function createImportObject() {
  const wasiNoop = () => 0;
  const wasiShim = {
    args_get: wasiNoop,
    args_sizes_get: wasiNoop,
    environ_get: wasiNoop,
    environ_sizes_get: wasiNoop,
    fd_close: wasiNoop,
    fd_fdstat_get: wasiNoop,
    fd_seek: wasiNoop,
    fd_write: wasiNoop,
    proc_exit: wasiNoop,
    random_get: wasiNoop,
    clock_time_get: wasiNoop,
  };
  const envShim = {
    abort: () => { },
    abort_: () => { },
    __assert_fail: () => { },
    emscripten_notify_memory_growth: () => { },
    memory: ENV_MEMORY,
    table: ENV_TABLE,
    __stack_pointer: new WebAssembly.Global({ value: "i32", mutable: true }, 0),
    __data_end: new WebAssembly.Global({ value: "i32", mutable: false }, 0),
    __heap_base: new WebAssembly.Global({ value: "i32", mutable: false }, 0),
  };
  return {
    wasi_snapshot_preview1: wasiShim,
    wasi_unstable: wasiShim,
    env: envShim,
  };
}

async function instantiateFromBase64() {
  const { instance } = await WebAssembly.instantiate(decodeBase64(EXTRACT_COLORS_WASM_BASE64), createImportObject());
  return instance;
}

async function instantiateFromUrl(resolvedUrl) {
  const importObject = createImportObject();
  if ("instantiateStreaming" in WebAssembly) {
    try {
      const { instance } = await WebAssembly.instantiateStreaming(fetch(resolvedUrl), importObject);
      return instance;
    } catch { }
  }
  const resp = await fetch(resolvedUrl);
  if (!resp.ok) throw new Error(`fetch extract-colors wasm failed: ${resp.status} ${resp.statusText}`);
  const buf = await resp.arrayBuffer();
  const { instance } = await WebAssembly.instantiate(buf, importObject);
  return instance;
}

async function loadExtractColorsWasm(options = {}) {
  if (_wasmPromise) return _wasmPromise;
  _wasmPromise = (async () => {
    const instance = options.wasmUrl
      ? await instantiateFromUrl(resolveWasmUrl(options.wasmUrl))
      : await instantiateFromBase64();
    const exports = instance.exports;
    const exportedMem = exports && exports.memory;
    const mem = exportedMem instanceof WebAssembly.Memory ? exportedMem : ENV_MEMORY;
    if (!mem) throw new Error("wasm memory not found");
    extractExports = exports;
    extractMemory = mem;
    return exports;
  })();
  return _wasmPromise;
}

async function ensureWasmReady(options) {
  if (extractExports) return;
  await loadExtractColorsWasm(options);
}

export async function initExtractColorsWasm(options) {
  await ensureWasmReady(options ?? {});
}

export default async function extractColors(input, opts) {
  await ensureWasmReady(opts);

  const toImageData = async () => {
    if (typeof input === "string") {
      const img = await new Promise((resolve, reject) => {
        const el = new Image();
        el.crossOrigin = (opts && opts.crossOrigin) ?? "";
        el.onload = () => resolve(el);
        el.onerror = () => reject(new Error("image load error"));
        el.src = input;
      });
      return extractImageDataViaCanvas(img, opts && opts.pixels);
    }
    if (isImageData(input)) return input;
    if (isImageDataAlt(input)) {
      const u8 = input.data instanceof Uint8ClampedArray ? input.data : new Uint8ClampedArray(input.data);
      return createImageDataFromRaw(u8, input.width, input.height);
    }
    return extractImageDataViaCanvas(input, opts && opts.pixels);
  };

  const imageData = await toImageData();
  if (!extractExports || !extractMemory) throw new Error("WASM 未就绪");

  const { width, height, data } = imageData;
  const hasCustomValidator = typeof (opts && opts.colorValidator) === "function";
  const len = data.byteLength >>> 0;
  const ptr = extractExports.get_pixels_buffer(len) >>> 0;
  if (!ptr) throw new Error("get_pixels_buffer 失败");
  const heapU8 = new Uint8Array(extractMemory.buffer, ptr, len);
  if (hasCustomValidator) {
    const validator = opts.colorValidator;
    for (let i = 0; i < len; i += 4) {
      const r = data[i];
      const g = data[i + 1];
      const b = data[i + 2];
      const a = data[i + 3];
      if (!validator(r, g, b, a)) {
        heapU8[i] = r; heapU8[i + 1] = g; heapU8[i + 2] = b; heapU8[i + 3] = 0;
      } else {
        heapU8[i] = r; heapU8[i + 1] = g; heapU8[i + 2] = b; heapU8[i + 3] = a;
      }
    }
  } else {
    heapU8.set(data);
  }

  const pixels = Math.max(1, Math.floor((opts && opts.pixels) ?? 64000));
  const distance = clamp01((opts && opts.distance) ?? 0.22);
  const satDist = clamp01((opts && opts.saturationDistance) ?? 0.2);
  const lightDist = clamp01((opts && opts.lightnessDistance) ?? 0.2);
  const hueDist = clamp01((opts && opts.hueDistance) ?? 1 / 12);
  const alphaThreshold = hasCustomValidator ? 1 : 250;
  const maxColors = 64;

  const outPtr = extractExports.extract_colors_from_rgba_js(
    ptr,
    width | 0,
    height | 0,
    pixels | 0,
    +distance,
    +satDist,
    +lightDist,
    +hueDist,
    alphaThreshold | 0,
    maxColors | 0
  ) >>> 0;
  if (!outPtr) throw new Error("extract_colors_from_rgba_js 失败");

  const f64 = new Float64Array(extractMemory.buffer, outPtr, 1 + 8 * 64);
  const m = Math.max(0, Math.min(64, Math.floor(f64[0])));
  const out = [];
  for (let i = 0; i < m; i++) {
    const base = 1 + i * 8;
    const red = Math.round(f64[base + 0]);
    const green = Math.round(f64[base + 1]);
    const blue = Math.round(f64[base + 2]);
    const hue = f64[base + 3];
    const intensity = f64[base + 4];
    const lightness = f64[base + 5];
    const saturation = f64[base + 6];
    const area = f64[base + 7];
    const hex = `#${[red, green, blue].map((v) => v.toString(16).padStart(2, "0")).join("")}`;
    out.push({ hex, red, green, blue, area, hue, saturation, lightness, intensity });
  }
  out.sort((a, b) => {
    const bPower = (b.intensity + 0.1) * (0.9 - b.area);
    const aPower = (a.intensity + 0.1) * (0.9 - a.area);
    return bPower - aPower;
  });
  return out;
}

function isImageData(x) {
  return x && typeof x === "object" && typeof x.width === "number" && typeof x.height === "number" && x.data instanceof Uint8ClampedArray;
}
function isImageDataAlt(x) {
  return x && typeof x === "object" && typeof x.width === "number" && typeof x.height === "number" && x.data && typeof x.data.length === "number";
}
function extractImageDataViaCanvas(source, targetPixels = 64000) {
  const canvas = getSharedCanvas();
  const ctx = getShared2DContext();
  const w0 = source.naturalWidth ?? source.videoWidth ?? source.width;
  const h0 = source.naturalHeight ?? source.videoHeight ?? source.height;
  const total = Math.max(1, (w0 | 0) * (h0 | 0));
  const scale = Math.min(1, Math.sqrt(Math.max(1, Math.floor(targetPixels)) / total));
  const w = Math.max(1, Math.round(w0 * scale));
  const h = Math.max(1, Math.round(h0 * scale));
  const needResize = canvas.width !== w || canvas.height !== h;
  if (needResize) {
    canvas.width = w; canvas.height = h;
    ctx.imageSmoothingEnabled = false; ctx.imageSmoothingQuality = "low";
  } else {
    ctx.clearRect(0, 0, w, h);
  }
  ctx.drawImage(source, 0, 0, w, h);
  return ctx.getImageData(0, 0, w, h);
}
function clamp01(n) { return Math.min(1, Math.max(0, Number(n))); }
function createImageDataFromRaw(data, width, height) {
  try { return new ImageData(data, width, height); }
  catch (_e) {
    const canvas = getSharedCanvas();
    const ctx = canvas.getContext("2d");
    const img = ctx.createImageData(width, height);
    img.data.set(data);
    return img;
  }
}
